openapi: 3.0.0
info:
  title: API per la Gestione delle Prenotazioni
  version: 1.0.0
  description: API per la gestione delle prenotazioni di sacchetti per la raccolta differenziata.

paths:
  /bookings:
    post:
      summary: Crea una nuova prenotazione
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                tipoSacchetto:
                  type: string
                quantita:
                  type: integer
                puntoRitiro:
                  type: string
      responses:
        '201':
          description: Prenotazione creata con successo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Prenotazione'
        '401':
          description: Accesso non autorizzato
        '500':
          description: Errore durante la creazione della prenotazione

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    User:
      type: object
      properties:
        nome:
          type: string
        cognome:
          type: string
        codiceFiscale:
          type: string
        telefono:
          type: string
        prenotazioni:
          type: array
          items:
            $ref: '#/components/schemas/Prenotazione'
    
    Prenotazione:
      type: object
      properties:
        utente:
          $ref: '#/components/schemas/User'
        tipoSacchetto:
          type: string
        quantita:
          type: integer
        dataPrenotazione:
          type: string
          format: date-time
        puntoRitiro:
          $ref: '#/components/schemas/PuntoRitiro'
        stato:
          type: string
          enum: ["in attesa", "confermato", "ritirato", "annullato"]

    PuntoRitiro:
      type: object
      properties:
        nome:
          type: string
        indirizzo:
          type: string
        orari:
          type: array
          items:
            type: object
            properties:
              giorno:
                type: string
              apertura:
                type: string
              chiusura:
                type: string
        tipiSacchetti:
          type: array
          items:
            type: string
