openapi: 3.0.0
info:
  title: API per la Raccolta Differenziata
  version: 1.0.0
  description: API per la gestione dei login e registrazione.
paths:
  /api/auth/login:
    post: 
      summary: Permette l'accesso a cittadini, operatori ecologici di Dolomiti Ambiente e operatori del Comune di Trento.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: Autenticazione avvenuta con successo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
  /api/auth/me:
    get:
      summary: Ottieni informazioni sull'utente autenticato
      description: Restituisce le informazioni sull'utente corrente e i suoi permessi.
      security:
        - bearerAuth: []  # Richiede autenticazione con token
      responses:
        '200':
          description: Informazioni sull'utente autenticato
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserInfoResponse'
        '401':
          description: Utente non autenticato
  /api/auth/signup:
    post:
      summary: Permette la registrazione di nuovi utenti.
      description: Endpoint per creare un nuovo account per cittadini, operatori ecologici di Dolomiti Ambiente o operatori del Comune di Trento. Gli operatori devono fornire un token segreto per garantire la sicurezza.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignupRequest'
      responses:
        '201':
          description: Registrazione avvenuta con successo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SignupResponse'
        '400':
          description: Errore nella richiesta di registrazione
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    LoginRequest:
      type: object
      properties:
        email: 
          type: string
          format: email
        password:
          type: string
      required:
        - email
        - password
    LoginResponse:
      type: object
      properties:
        token: 
          type: string
        role: 
          type: string
          enum: [cittadino, operatore_Dolomiti, operatore_comune]
        permission:
          type: array
          items: 
            type: string
    UserInfoResponse:
      type: object
      properties:
        user_id:
          type: string
        role:
          type: string
          enum: [cittadino, operatore_dolomiti, operatore_comune]
        permissions:
          type: array
          items:
            type: string
    SignupRequest:
      type: object
      properties:
        email:
          type: string
          format: email
        password:
          type: string
          format: password
        name:
          type: string
        role:
          type: string
          enum: [cittadino, operatore_Dolomiti, operatore_comune]
        secret_token:
          type: string
          description: Token segreto richiesto per registrarsi come operatore.
      required:
        - email
        - password
        - name
        - role
      anyOf:
        - properties:
            role:
              enum: [operatore_Dolomiti, operatore_comune]
            secret_token:
              type: string
          required:
            - secret_token
        - properties:
            role:
              enum: [cittadino]
    SignupResponse:
      type: object
      properties:
        message:
          type: string
        user_id:
          type: string
    ErrorResponse:
      type: object
      properties:
        error:
          type: string
